### PR TITLE
Update moderntimeline.dtx

### PR DESCRIPTION
**Pull request by Astrinus**
Shaded entries have a first part not shaded.

### CODE REVIEW

**Comment by raphink** [comment]
Thank you and welcome to github!

Could you please describe what this does exactly (maybe with images) and if
this changes the existing behaviour?

**Comment by raphink** [comment]
Also, it seems that the change breaks the tests. See
https://travis-ci.org/raphink/moderntimeline/builds/51128930

**Comment by Astrinus** [comment]
It doesn't change the existing behaviour. It simply changes slightly the appearance of the bars.
schermata1
The shading goes for 40% to 100% of the bar length instead of 0%-100%, in some cases (especially if the base color is dark) it is rendered better.

**Comment by raphink** [comment]
OK. Maybe this 0.4 value could become a parameter, so it would be backwards
compatible and allow users to fine tube the rendering.

**Comment by Astrinus** [comment]
I have created a new macro, \tlsetnotshadedfraction, and updated my branch. This is the first time I use Git, so I don't know if I should make another pull request.

**Comment by Astrinus** [comment]
Well... I didn't know there was a CheckSum line in the .dtx :-$

**Comment by Astrinus** [comment]
And I didn't know about pdf_spec.rb... By the way, one of the failures pertains the last check: I have commented it out, but I don't know Ruby or how rspec works.

**Comment by Astrinus** [comment]
Yes, it adds a new page (description of \tlsetnoshadedfraction causes text to overflow) and I don't know why the title error arises, since the file looks good being opened with Okular...

**Comment by raphink** [comment]
Makes sense for the number of pages. However the title issue is strange. I'll have to try it and see why it fails.

**Comment by raphink** [comment]
Merged as 7299b89aab4b8e8fe2486ac0ae52b609b261ae07, thank you.

**Comment by raphink** [comment]
Released as 0.8

**Pull request closed without merging**
