### PR TITLE
Month support

### PR DESCRIPTION
**Pull request by Astrinus**
I've added support for months to resolve the issue I have open last week.

### CODE REVIEW

**Comment by Astrinus** [comment]
It is strange: on my system the PDF is 9 pages, but on Travis 11 are generated.

**Comment by raphink** [comment]
Sorry for the delay. Could you remove 37b9db2fd699f3fb58b1293d3283670c011f5a65 and squash the other commits please?

**Comment by Astrinus** [comment]
How can I do this?

**Comment by raphink** [comment]
Use `git rebase -i HEAD~4`, remove the line for the additional commit and squash the other ones, then do a push force on the feature branch.

**Comment by raphink** [comment]
Merged as d8adf92eaa842ca54715debd4bf4762c17b21394

**Comment by raphink** [comment]
This was now released in version 0.9.

**Pull request closed without merging**
